// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2IlGoaxMi3ttyCYURvaBLtS205sLbQI8',
    appId: '1:205067876404:web:3ce9929520e39c632ef261',
    messagingSenderId: '205067876404',
    projectId: 'caddenetwork-app',
    authDomain: 'caddenetwork-app.firebaseapp.com',
    storageBucket: 'caddenetwork-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFKr6U1-t_z33ezapJQClklG5V4mqxebk',
    appId: '1:205067876404:android:ce5d1ddd1b03aca92ef261',
    messagingSenderId: '205067876404',
    projectId: 'caddenetwork-app',
    storageBucket: 'caddenetwork-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkXTJjGtBkNYKLpXrbvMc8aYOdxGCsm8w',
    appId: '1:205067876404:ios:3dd23199714ed1172ef261',
    messagingSenderId: '205067876404',
    projectId: 'caddenetwork-app',
    storageBucket: 'caddenetwork-app.firebasestorage.app',
    iosBundleId: 'com.example.caddenetwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkXTJjGtBkNYKLpXrbvMc8aYOdxGCsm8w',
    appId: '1:205067876404:ios:3dd23199714ed1172ef261',
    messagingSenderId: '205067876404',
    projectId: 'caddenetwork-app',
    storageBucket: 'caddenetwork-app.firebasestorage.app',
    iosBundleId: 'com.example.caddenetwork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2IlGoaxMi3ttyCYURvaBLtS205sLbQI8',
    appId: '1:205067876404:web:70ac6645b043f8bc2ef261',
    messagingSenderId: '205067876404',
    projectId: 'caddenetwork-app',
    authDomain: 'caddenetwork-app.firebaseapp.com',
    storageBucket: 'caddenetwork-app.firebasestorage.app',
  );
}
